title: wuzy
description: O ever youthful, O ever weeping

menu:
  Home: /
  #About: /about
  Github: https://github.com/zywudev
  #Email: mailto:zywu.dev@gmail.com
  #Blogroll: /blogroll
  #Rss: /atom.xml

rss: /atom.xml

# your name
signoff: Scribble

# disqus comment thread for post header options ( leave blank if unwanted )
disqus_shortname: wuzhangyang

# set tracking, UA-XXXX-Y
google_analytics: 
