# Page language (html attribute)
language: en

# Main menu navigation items
menu:
  Blog: /
  Archives: /archives
  About: /about
  # Title: /pageName - create using `hexo new page 'pageName'`

# Post social sharing features
social:
  twitter: your_twitter # set to your twitter handle

# Page sidebars
# Components will appear in the order they are specified
sidebars:
  wechat: true
  recent: true # boolean to display 10 most recent posts
  featured: false # boolean to list all posts with tag 'featured'
  github: false # string to point to a Github profile | false to disable

# Disqus comments
disqus:
  enabled: true
  shortname: wuzhangyang

# Analytics
googleAnalytics: UA-127464210-1 # false | string (UA-xxxx ID)

# Link to atom.xml in nav bar?
# You can use https://github.com/hexojs/hexo-generator-feed to generate these
atom: false

# Stylesheets loaded in the <head>
stylesheets:

# Scripts loaded at the end of the body
scripts: